services:
  backend:
    build:
      context: ../bookinghub-backend
    container_name: bookinghub_backend
    ports:
      - "8000:8000"
    volumes:
      - ../bookinghub-backend:/app
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ../bookinghub-frontend
    container_name: bookinghub_frontend
    ports:
      - "3000:3000"
    volumes:
      - ../bookinghub-frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  db:
    image: postgres:16
    container_name: bookinghub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data:
